language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: StkNqNyESzB2EXttgztCD/y2+6wC/A91mxNkcAy3R9rLuy0gPmXwfN6Hnbo3Y0lOUIKZjDWJvKPt1WKrVIyoffjr1M7zVWJU6aADfiTD++nOlDjum/W6uh+UEHXUEJrDmcNGWP0G+FGdlCDqPP2ed3HEKzizJ6Oas94QUMjo7cdyE9lMYOi8aSZz6ZQ6aGdVYT1W8zYEyx8ieq7rlNu6eqU8KY6IG5/ckVJOZAmoEmG1rsd42qr9s3ZTpWWzYzvVJm0I/3xv4c8f22pKORJta9FI7OtTvhHNZB+XPDD8AvDKMq8t6JuW8KKB2zIb/VVfOV8fT/kAOvQPv1Xt8esl13gsS5XsOpf96N1M4vIP777Js1l1VoPkeJ/WAyQEGRmu7RZ3MJEo9iINdYvzL/b0wZt15w4WR0MIjP44Yc03NFbl+r4BSx7hQu6rk3HZdw3412QJutNiU2Xs+9m81b5PK8wMm5Ay7loApcejdXXTt2Pi67039P1ImSdpL03G+IhMrP2jlpQL5bhdsrO+MEQpVIoqMh0K5HDcTeFyLX2UIXjaoA1Ud0FYQXKQrbSXBp/UM+5LXur/xuYAxDnkgvRtAkGn6k1N+V5OBbehzNghIQ+0EJ5uun7br1heorDoWwJpse82cbWtEiHY/g0ZA+FLsXcX37uFR6cH7Epc1aO0+hE=
  - secure: GHO+nqvwSVDFKiQWj2e7aXSESIhWeGwoE5Dn5lLqsBlrSh6T0N5MXXavvDEaVsb9E8wGgoUlSDk8ducM0/vINBbGwo63g7zT0NekZMUlsHOYma25kC4YbAnlgDMazN8kIj7NVRqIAg8MlvynkzF88dLB2CEbCjBaKHCCW7ci5++2pB5R5p7fJAr+rWzL9jpM7vbUsY+7/Kba+v2rGZwWxjdD/XEaUQRjccwFYqgsETBv9miqWjFiW0Qiwuk1UpBO2k67Q+NnMjB0B8ThofoO416nhKHLX+VI4TXu2L+FZ1BEK5B+87zdBmatL6YHSDWyrYTbZBAPLE2c9wnwd3H5Er9uo/3P+IiScdbAr3+Hcy90d20Jw3FVVh6IrdLTkcDKXVDEmAjFOW4Sh9tYe+pdXeEseLntr2fil7xPND+U3conZEEPzaXtKed9kmCnIBC68C0fAi5bFYEgBqv5eqwNpBNgSNQ/sov9zcsSZryK1oeyJ9dGTj65alLuGyzf8hzhl3Ur4ZjbMYSbzH7x9T6EWdPAHwIZ4uwwewQDL3e2Ulpx1N5/6nfRotcJa3zfxC6zpXKdUycOx5SLtTalpk+eXQMee/dd5mG6UXnSrqUOfPvq2msKlrIo1ZYKlRBa1WbvcOuKENjcwffix90OENES5/VHdyQUhgHmSRNy278WNpc=
